"""add user roles

Revision ID: 3455961c8104
Revises: 03c85a9a9116
Create Date: 2026-01-13 14:11:30.029835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3455961c8104'
down_revision: Union[str, Sequence[str], None] = '03c85a9a9116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to be idempotent ###
    bind = op.get_bind()
    # Add columns if not exists (Postgres supports IF NOT EXISTS)
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_superuser BOOLEAN DEFAULT false')
    op.execute('ALTER TABLE "user" ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true')

    # Ensure any existing NULLs are populated, then make columns NOT NULL
    op.execute('UPDATE "user" SET is_superuser = false WHERE is_superuser IS NULL')
    op.execute('UPDATE "user" SET is_active = true WHERE is_active IS NULL')

    op.execute('ALTER TABLE "user" ALTER COLUMN is_superuser SET NOT NULL')
    op.execute('ALTER TABLE "user" ALTER COLUMN is_active SET NOT NULL')

    # Optionally remove the server default if you don't want it persisted
    op.execute('ALTER TABLE "user" ALTER COLUMN is_superuser DROP DEFAULT')
    op.execute('ALTER TABLE "user" ALTER COLUMN is_active DROP DEFAULT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###
