"""add status to item

Revision ID: aecea27efcf4
Revises: 0ed9aa63a156
Create Date: 2026-01-12 14:09:32.608141

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aecea27efcf4'
down_revision: Union[str, Sequence[str], None] = '0ed9aa63a156'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'status')
    # ### end Alembic commands ###
