"""add user and item owner

Revision ID: f0d1c444d4bb
Revises: aecea27efcf4
Create Date: 2026-01-12 14:21:51.355974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0d1c444d4bb'
down_revision: Union[str, Sequence[str], None] = 'aecea27efcf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # Add owner_id as nullable so we can populate existing rows first
    op.add_column('item', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item', 'user', ['owner_id'], ['id'])

    # Insert a fallback owner and assign to existing items that have no owner
    bind = op.get_bind()
    # Create a default owner email; adjust as needed
    default_email = "import-owner@example.com"
    default_password = "changeme"
    # Insert and get the new user's id (Postgres RETURNING)
    result = bind.execute(sa.text(
        'INSERT INTO "user" (email, hashed_password) VALUES (:email, :pwd) RETURNING id'
    ), {"email": default_email, "pwd": default_password})
    owner_id = result.fetchone()[0]
    # Update existing items to reference the new owner
    bind.execute(sa.text('UPDATE item SET owner_id = :owner_id WHERE owner_id IS NULL'), {"owner_id": owner_id})

    # Now that column is populated, make it NOT NULL
    op.alter_column('item', 'owner_id', existing_type=sa.Integer(), nullable=False)

    # remove deprecated 'status' column
    op.drop_column('item', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_column('item', 'owner_id')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
